name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rocq
        uses: rocq-community/docker-coq-action@v1.5.2
        with:
          opam_file: "rocq-cats.opam"
          custom_script: |
            dune build
