name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - "rocq/rocq-prover:latest"
          - "rocq/rocq-prover:dev"
          - "rocq/rocq-prover:9.1"
          - "rocq/rocq-prover:9.0"
    steps:
      - uses: actions/checkout@v4
      - name: Install Rocq
        uses: rocq-community/docker-coq-action@v1
        with:
          opam_file: "rocq-cats.opam"
          custom_image: ${{ matrix.image }}
          export: "OPAMWITHTEST"
        env:
          OPAMWITHTEST: "true"
